// Generated by Wrangler by running `wrangler types`

interface Env {
	SERVICE_KEY: string;
	BUSINESS_QUERY_API_URL: string;
	JUSO_API_URL: string;
	JUSO_API_KEY: string;
	NAVER_CLIENT_ID: string;
	NAVER_CLIENT_SECRET: string;
	NAVER_REDIRECT_URI: string;
	DB: D1Database;
	JWT_SECRET: string;
	JWT_ISSUER: string;
	JWT_AUDIENCE: string;
}
