name = "nomubackend"
main = "worker.js"
compatibility_date = "2024-01-01"

# Custom domain configuration
[[routes]]
pattern = "api.nomu.buildman.kr/*"
zone_name = "buildman.kr"

[env.production]
name = "nomubackend-prod"

[env.staging]
name = "nomubackend-staging"

# KV Namespace for additional caching (optional)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Environment variables (optional)
[vars]