name = "nomubackend"
main = "worker.ts"
compatibility_date = "2024-01-01"

[observability.logs]
enabled = false

[[d1_databases]]
binding = "DB"
database_name = "nomu-db"
database_id = "10102c31-11e2-4c86-8b6c-51cf9aaba78e"
migrations_dir = "prisma/migrations"

[env.production]
name = "nomubackend"

[env.staging]
name = "nomubackend-staging"

# 개발 환경 설정
[env.development]
name = "nomubackend-dev"

# 환경 변수 (실제 값으로 변경 필요)
[vars]
# 근로복지공단 API 키
SERVICE_KEY = "iaxjwmL9Hxpw3MSZ6XSYR0wcx1bWX0+18BmyAuILHPob+Qjn/F+Vt3sez2SsejjveYC0Ck+4EsAENKZ6JB2jTA=="
INDUSTRIAL_ACCIDENT_INSURANCE_PREMIUM_RATE_API_URL = "https://apis.data.go.kr/B490001/gySjbPstateInfoService/getEopjongSjBoheomTariffPyoPstateList"

# 도로명주소 API 키
JUSO_API_URL = "https://business.juso.go.kr/addrlink/addrLinkApiJsonp.do"
JUSO_API_KEY = "U01TX0FVVEgyMDI1MDgwMzAyNDUwOTExNjAxNTg="

# 네이버 OAuth 설정
NAVER_CLIENT_ID = "iG_coo1OuyZewmYWIxgO"
NAVER_CLIENT_SECRET = "ZF4vuQd7JA"
NAVER_REDIRECT_URI = "http://localhost:3000/auth/naver-callback"

# JWT 설정
JWT_SECRET = "BuildmanSecretKey12345678901234567890"
JWT_ISSUER = "Buildman"
JWT_AUDIENCE = "Buildman"